### ISSUE TITLE
Error after health check

### ISSUE THREAD

**Issue by bryanpcall** [KingdomFirst/Excavator#178]
I keep getting this:
6/29/2017 10:52:19 PM,Transform Data,"System.ComponentModel.Win32Exception (0x80004005): The network path was not found"

I am trying to upload CSV
Files match column for column as instructed
Connection to database OK

Fails after the health check.

Suggestions?

**Comment by rutledgek** [comment]
I'm actually having the same problem.

**Comment by waynepaulj** [comment]
Trying to import a family file using the latest excavator.exe from 7/16/2017.  Everything worked smoothly when I used excavator in 2016.  
First, the "Select / Preview" screen is blank.  The first record is not displayed.
Secondly, at the end of the import the following displays:
11:29:40 AM  Starting health checks...
11:30:07 AM  Checking for existing people...
11:30:11 AM  Starting data import...
11:30:11 AM  Completed import: 0 rows processed.
11:30:11 AM  Could not finish upload. Check the exceptions log for details.

After closing the program, there is not a log fine in the logs folder.
Not sure what I am doing wrong.  Any suggestions will be appreciated.

**Comment by scridget** [comment]
We are also having a similar issue of the excavator failing after/during the health check.. Our error is that "The system could not the file specified". We're running everything as administrator, and have all permissions opened up on the files themselves. It seems like it's able to read the file in the columns preview before the import, but it fails every time.

**Comment by scridget** [comment]
Actually! Just found my answer here: https://github.com/NewSpring/Excavator/issues/170

**Comment by dcs619** [comment]
#170 was the connection string not being set correctly, but if the Select / Preview screen is blank then Excavator wasn't able to read your import file.

If you have a running Rock instance you can copy the `<RockContext>` string out of RockWeb\web.connectionstrings.config and paste that into Excavator.exe.config.  Don't change the connection string from the app (it will load from the config file) and see if that works.
