### ISSUE TITLE
Individuals not showing up in directory.

### ISSUE THREAD

**Issue by dustin515** [KingdomFirst/Excavator#187]
We were able to import and individuals show up in the global search but not in the directory.  Is there a way to correct this?

**Comment by treyhendon** [comment]
The Directory as in, under the page nav `People > Directory`?  That block filters the Directory in a Block setting.  By default it shows the `Members & Attendees` Data View.

**Comment by dcs619** [comment]
Closing, could not reproduce.  Directory display is determined by Connection Status	(default Member or Attendee).
