### ISSUE TITLE
Any experience using Excavator with Rock 7.x?

### ISSUE THREAD

**Issue by garyholeman** [KingdomFirst/Excavator#191]
We used Excavator to successfully pull .CSV records into Rock 6.3.  This was in preparation for converting right before going live.  Now we are on 7.3 and importing using the same .CSV files we used before.  Now I am receiving errors.  The message from the log file is below.  Any insight as to why?

2/28/2018 22:12 | Transform Data | System.Data.SqlClient.SqlException   (0x80131904): Invalid column name 'MustMeetRequirementsToAddMember'.             at   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean   breakConnection, Action`1 wrapCloseInAction)             at   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject   stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)             at   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand   cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet   bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)             at   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()             at   System.Data.SqlClient.SqlDataReader.get_MetaData()             at   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds,   RunBehavior runBehavior, String resetOptionsString, Boolean isInternal,   Boolean forDescribeParameterEncryption)             at   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior   cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async,   Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry,   SqlDataReader ds, Boolean describeParameterEncryptionRequest)             at   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior   cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method,   TaskCompletionSource`1 completion, Int32 timeout, Task& task,   Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)             at   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior   cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String   method)             at   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior,   String method)             at   System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget   target, Func`3 operation, TInterceptionContext interceptionContext, Action`3   executing, Action`3 executed)             at   System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand   command, DbCommandInterceptionContext interceptionContext)             at   System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand   entityCommand, CommandBehavior behavior)          ClientConnectionId:fcb7b78a-f138-47c5-9a50-394df108d2b4          Error Number:207,State:1,Class:16
-- | -- | --

**Comment by garyholeman** [comment]
As a followup, I setup a Rock 6.x environment again and was able to import the same .CSV files, so it appears that Excavator will not currently work with a 7.x database.

**Comment by dcs619** [comment]
That's correct. Rock v7 is in Early Release until May (?) 2018 and contains "breaking" changes so Excavator has not been updated yet.

**Comment by dcs619** [comment]
Excavator has been updated to Rock 7.3
