### ISSUE TITLE
Problem with Import

### ISSUE THREAD

**Issue by poder75** [KingdomFirst/Excavator#192]
Currently installed verison 6.10 of rockrms.  Attempting to populate records from CSV.

When i run the individual import using Excavator, I get this error;

Transform Data,"System.IndexOutOfRangeException: Index was outside the bounds of the array. at Excavator.CSV.CSVComponent.LoadIndividuals(CSVInstance csvData) at Excavator.CSV.CSVComponent.TransformData(Dictionary`2 settings) at Excavator.ProgressPage.bwImportData_DoWork(Object sender, DoWorkEventArgs e)"

Any help would be greatly appreciated.

Thanks,

**Comment by treyhendon** [comment]
It sounds like the CSV file doesn't have the proper number of columns.  Did you use the Sample CSVs ( https://github.com/NewSpring/Excavator/tree/master/Excavator.CSV/SampleCSVs ) and include the same columns?  All the columns have to exist in the file, so if there's not data for a field (i.e. `SubFundName`), it should be left blank on all the rows.

**Comment by dcs619** [comment]
Closing, could not reproduce using sample data.
