### ISSUE TITLE
Import error - invalid object name dbo.DefinedValue

### ISSUE THREAD

**Issue by knolly42** [KingdomFirst/Excavator#195]
Hi any idea why I'm getting an import error on 7.3:
07/06/2018 00:24:19,Transform Data,"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.DefinedValue'.

I unblocked each file, then chose CSV as the import, localhost/Rock as the db.

Connection to file and db are fine.

hope you can help

thanks

**Comment by dcs619** [comment]
If your connection string is correct, then you must've defined a custom schema for the Rock database or you don't have a DefinedValue table.  Excavator uses the RockContext data layer and Rock-provided entity services; the codebase never references  `dbo.DefinedValue`.
