### ISSUE TITLE
CSV: Back button bug

### ISSUE THREAD

**Issue by mikejed** [KingdomFirst/Excavator#86]
This is not keeping me from importing- I have worked out my data issues and can import 100% without touching the back button now, but I had been using it to narrow down the ranges wherein there were import-breaking data errors and noticed a pattern I thought you should be aware of.

Upon the import failing to save the previous 50 individuals, if the user presses back and then clicks the "import" button again (or whatever the button is labeled) from the final configuration screen, it appears that the intended behavior is that it would begin with the next individual and try to save the next 50 individuals' complete families. But there's some kind of n+1 error at some point, because it actually skips the next person and starts with the second.

For example: let's say it loads the first 50 people (lines 2-51 on the CSV) and tries, but fails, to save them. The error pops up and the import halts. The user presses Back and then immediately re-commences the import without restarting the program. Excavator reports the name of the person on the new row #1, which should be the person on line 52. But instead, it skips line 52 and the person on line 53 is used as row 1 in Excavator's output. I did check in the ROCK database to make sure it wasn't just an output error, but the person who appeared to be skipped was indeed missing.

Thanks for all your work on this ESSENTIAL tool!!

**Comment by treyhendon** [comment]
My guess is that it has to do with the dataset advancing the row prior to the back button and then when restarting it advances again.  I think it might be best to disable the back button (preventing the scenario) and adding a Stop button which would clear the location and re-enable the back button.  Just ideas for the enhancement.

**Comment by dcs619** [comment]
Closing, not a priority to implement.
